name: agnostos
channels:
  - conda-forge
  - bioconda
  - intel
  - r
dependencies:
  - impi_rt=2019.9=intel_304
  - parallel
  - bbmap
  - prodigal
  - seqtk
  - seqkit
  - datamash
  - coreutils
  - ripgrep
  - mcl
  - pandoc
  - vmtouch
  - r-base=3.6.3
  - r-rcpp
  - r-dplyr
  - r-dbi
  - r-tidyverse
  - r-data.table
  - r-proxy
  - r-stringr
  - r-vegan
  - r-splitstackshape
  - r-cowplot
  - r-rsqlite
  - r-dbplyr
  - r-knitr
  - r-rmarkdown
  - r-markdown
  - r-kableExtra
  - r-ggrepel
  - r-ggsci
  - r-optparse
  - r-proxy
  - r-zoo
  - r-stringi
  - r-igraph
  - r-tidygraph
  - r-crayon
  - r-bigreadr
  - r-foreach
  - r-itertools
  - r-dosnow
  - r-entropy
  - r-ggridges
  - r-ggrepel
  - r-unix
  - r-pbmcapply
  - r-maditr
  - r-r.utils
  - r-stringdist
